import { db } from './firebase.js';
import { collection, doc, setDoc, addDoc, deleteDoc, query, onSnapshot, where, serverTimestamp } from "[https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js](https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js)";

let unsubscribeRequests=null, currentWeeklyLogUnsubscribe=null;

window.openWriteModal = function() { window.editingReqId = null; document.getElementById('req-project-name').value = ''; document.getElementById('req-title').value = ''; document.getElementById('write-modal').classList.remove('hidden'); document.getElementById('write-modal').classList.add('flex'); };
window.closeWriteModal = function() { document.getElementById('write-modal').classList.add('hidden'); document.getElementById('write-modal').classList.remove('flex'); };
window.saveRequest = async function(btn) {
    const title = document.getElementById('req-title').value; if(!title) return window.showToast("제목을 입력하세요", "error");
    btn.disabled=true; btn.innerHTML='저장중...';
    try { const data = { type: window.currentAppId, status: 'pending', title: title, authorUid: window.currentUser.uid, authorName: window.userProfile.name, authorTeam: window.userProfile.team, updatedAt: serverTimestamp() }; if(window.editingReqId) { await setDoc(doc(db,"requests",window.editingReqId), data, {merge:true}); } else { data.createdAt = serverTimestamp(); await addDoc(collection(db,"requests"), data); } window.showToast("등록 완료"); window.closeWriteModal(); } catch(e) { window.showToast("에러", "error"); } finally { btn.disabled=false; btn.innerHTML='저장하기'; }
};
window.loadRequestsData = function(appId) { if(unsubscribeRequests) unsubscribeRequests(); unsubscribeRequests = onSnapshot(query(collection(db, "requests"), where("type", "==", appId)), (s) => { window.currentRequestList=[]; s.forEach(d=>window.currentRequestList.push({id:d.id,...d.data()})); window.currentRequestList.sort((a,b)=>(b.createdAt?.toMillis()||0)-(a.createdAt?.toMillis()||0)); if(window.renderRequestList) window.renderRequestList(); }); };
window.renderRequestList = function() { const tb = document.getElementById('request-tbody'); if(!tb) return; if(window.currentRequestList.length===0) { tb.innerHTML='<tr><td colspan="6" class="text-center p-8">데이터 없음</td></tr>'; return; } tb.innerHTML = window.currentRequestList.map(r=>`<tr class="hover:bg-slate-50"><td class="p-4 font-bold text-indigo-700">${r.title}</td><td class="p-4 text-xs">${r.authorName}</td><td class="p-4"><button onclick="window.deleteRequest('${r.id}')" class="text-slate-400 hover:text-rose-500"><i class="fa-solid fa-trash-can"></i></button></td></tr>`).join(''); };
window.deleteRequest = async function(id) { if(confirm("삭제할까요?")){ await deleteDoc(doc(db,"requests",id)); window.showToast("삭제됨"); } };

window.openWeeklyLogWriteModal = function(id=null) { document.getElementById('weekly-id').value = id||''; document.getElementById('weekly-content').value = ''; document.getElementById('weekly-week').value = window.getWeekString?window.getWeekString(new Date()):''; document.getElementById('weekly-log-write-modal').classList.remove('hidden'); document.getElementById('weekly-log-write-modal').classList.add('flex'); };
window.closeWeeklyLogWriteModal = function() { document.getElementById('weekly-log-write-modal').classList.add('hidden'); document.getElementById('weekly-log-write-modal').classList.remove('flex'); };
window.saveWeeklyLog = async function() { const id=document.getElementById('weekly-id').value, week=document.getElementById('weekly-week').value, content=document.getElementById('weekly-content').value.trim(); if(!week||!content)return window.showToast("주차/내용 입력","error"); try { if(id) await setDoc(doc(db,"weekly_logs",id),{week,content,updatedAt:serverTimestamp()},{merge:true}); else await addDoc(collection(db,"weekly_logs"),{week,content,authorUid:window.currentUser.uid,authorName:window.userProfile.name,createdAt:serverTimestamp()}); window.showToast("저장됨"); window.closeWeeklyLogWriteModal(); } catch(e){} };
window.loadWeeklyLogsData = function() { const w=document.getElementById('weekly-log-filter-week').value; if(!w)return; if(currentWeeklyLogUnsubscribe) currentWeeklyLogUnsubscribe(); currentWeeklyLogUnsubscribe = onSnapshot(query(collection(db,"weekly_logs"),where("week","==",w)), s=>{ window.currentWeeklyLogList=[]; s.forEach(d=>window.currentWeeklyLogList.push({id:d.id,...d.data()})); window.currentWeeklyLogList.sort((a,b)=>(b.createdAt?.toMillis()||0)-(a.createdAt?.toMillis()||0)); if(window.renderWeeklyLogs) window.renderWeeklyLogs(); }); };
window.renderWeeklyLogs = function() { const g=document.getElementById('weekly-log-grid'); if(!g)return; g.innerHTML=window.currentWeeklyLogList.map(l=>`<div class="bg-white rounded-2xl border p-5 shadow-sm"><div class="flex justify-between mb-3"><span class="font-black text-xs">${l.authorName}</span><button onclick="window.deleteWeeklyLog('${l.id}')" class="text-rose-500"><i class="fa-solid fa-trash-can"></i></button></div><div class="text-sm whitespace-pre-wrap">${l.content}</div></div>`).join(''); };
window.deleteWeeklyLog = async function(id) { if(confirm("삭제할까요?")){ await deleteDoc(doc(db,"weekly_logs",id)); window.showToast("삭제됨"); } };
